name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: enaccord_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Droits d'exécution sur mvnw
        run: chmod +x mvnw

      # Compilation seule de l'application
      - name: Compilation de l'application
        run: ./mvnw -B clean compile -DskipTests

      #  Exécution exclusive des tests unitaires
      - name: Tests Unitaires EnAccord
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/enaccord_test
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        run: ./mvnw -B surefire:test

      #  Exécution exclusive des tests d'intégration et JaCoCo
      - name: Tests d'Intégration EnAccors
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/enaccord_test
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        run: ./mvnw -B failsafe:integration-test failsafe:verify

      #  Analyse de la qualité du code
      - name: Analyse SonarCloud
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/enaccord_test
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tomtom100290 -Dsonar.organization=tomtom100290